CREATE TABLE CARDDEMO.TRANSACTION_TYPE_CATEGORY
(   TRC_TYPE_CODE                  CHAR(2) NOT NULL,
    TRC_TYPE_CATEGORY              CHAR(4) NOT NULL,
    TRC_CAT_DATA                   VARCHAR(50) NOT NULL,
    PRIMARY KEY(TRC_TYPE_CODE,TRC_TYPE_CATEGORY),
    FOREIGN KEY TRC_TYPE_CODE (TRC_TYPE_CODE)
    REFERENCES CARDDEMO.TRANSACTION_TYPE (TR_TYPE) ON DELETE RESTRICT);
